### ISSUE TITLE
Fuzzy search Quality

### ISSUE THREAD

**Issue by mathiasberggren** [mathiasberggren/streaming-subscription#22]
Right now we're using trigrams to match in the database which is not the best.

For example the following search keyword "matris" would match "The Matrix" while it would not match "The Matrix Reloaded". 

We should add a better way to fuzzy search this.

Optimally we would also take into consideration which movies are the most popular when searching

**Comment by rasouza** [comment]
Found [this solution](https://www.freecodecamp.org/news/fuzzy-string-matching-with-postgresql/) about applying fuzzy search with arrays

> Perhaps you only have an idea of one part of the name. The % operator lets you compare against elements of an array, so you can match against any part of the name. The next query uses Postgres' STRING_TO_ARRAY function to split the artists' full names into arrays of separate names.

```
SELECT
	*
FROM artists
WHERE 'Cadinsky' % ANY(STRING_TO_ARRAY(name,' '));`
```
![image](https://github.com/mathiasberggren/streaming-subscription/assets/337906/470a03e4-de31-469d-8db5-e184149712ae)

Do you think that might work?

**Comment by rasouza** [comment]
I've just tested and it works, will throw a PR for that :D
